spring:
 
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa 
  jpa:
    hibernate: 
      ddl-auto: update   
    properties:
        javax:
          persistence:
            validation:
               mode: none
 
  data: 
    web:
      pageable:
        default-page-size: "5"
        max-page-size: "100"

  profiles:
    active:
    - dev
  servlet: 
    multipart:
      max-file-size: 10MB
        
   
    
---
spring: 
  profiles: dev
hoaxify: 
    upload-path: picture
  